### ISSUE TITLE
series is in option

### ISSUE THREAD

**Issue by hustcc** [somonus/react-echarts#3]
In echarts‘s API, `series` is part of `option`.

Why configure them individually? Why not configure them only in option?

**Comment by somonus** [comment]
In my opinion, line chart and bar chart are different react components. 
So they should be separated, and they can be freely combined.

**Comment by hustcc** [comment]
Why not be consistent with `Baidu echarts`?

**Comment by somonus** [comment]
I can make it be compatible with echarts.
But in react, components should not be defined in the property.

**Comment by somonus** [comment]
In my next version，I will be compatible with the echarts's option.
