### ISSUE TITLE
treemap 类型画不出来 传入类型不起作用

### ISSUE THREAD

**Issue by SidFeng** [somonus/react-echarts#4]
`const options = {
      title: {
        text: 'Disk Usage',
        left: 'center'
      },
      series: [{
        name:'Disk Usage',
        type:'treemap',
        itemStyle: {
          normal: {
            borderColor: '#fff'
          }
        },
        data: [
          {
            name: '苹果',
            value: 6
          },
          {
            name: '香蕉',
            value: 4
          },
          {
            name: '猕猴桃',
            value: 4
          },
          {
            name: '梨',
            value: 2
          },
          {
            name: '橙子',
            value: 2
          },
          {
            name: '桔子',
            value: 1
          },
          {
            name: '西瓜',
            value: 1
          }]
      }]
    }
`

`<Chart options={ options } onReady={this.ready} />`

**Comment by somonus** [comment]
你用哪个版本？

**Comment by SidFeng** [comment]
"rc-echarts": "^0.3.0"

**Comment by somonus** [comment]
我测试了一下你的代码是可以正常展示的，完整代码贴一下？
